### ISSUE TITLE
Typo in Version Badge

### ISSUE THREAD

**Issue by aaishikasb** [srm-kzilla/mellow-vscode-theme#1]
- File: README.md
- Label: Documentation
- Line: 16
- Code: `<img src="https://img.shields.io/badge/verion-0.0.1-yellowgreen" alt="version 0.0.1"/>`
- Fix: verion -> version

**Comment by sachdeva-shrey** [comment]
Nice find! Can you create a PR for the same and I'll merge it in `master`?
